records/urls.py
from django.urls import path
from records import views
from django.contrib.auth import views as auth_views


app_name= 'records'
urlpatterns = [
    path('list/', views.students_list, name="NameOfStudents"),
    path('register/', views.register, name="registerstudents"),
    path('editmode/',views.editmode, name="editmode"),
    path('editmode1/',views.editmode1, name="editmode1"),
    path('upload/', views.upload, name="uploads"),
    path('search/', views.search, name="search"),
    path('delete/<int:pk>', views.delete, name="delete"),
    path('edit/<int:pk>', views.edit, name="edit"),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    
]

sagarmatha/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('records.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/models.py
from django.db import models
from django.db.models import CharField
from datetime import datetime    



class list_students(models.Model):
    name = models.CharField(max_length=100, unique=False,null=True)
    birthdate = models.DateTimeField(default=datetime.now(),help_text="Please specify english date: <em>YYYY-MM-DD</em>.")
    placeofbirth= models.CharField(max_length=200, null=True,blank=True)
    FATHERLESS = 'Fatherless'
    MOTHERLESS = 'Motherless'
    PARENTS = 'Parents'
    family_stat = (
        (FATHERLESS, 'Fatherless'),
        (MOTHERLESS, 'Motherless'),
        (PARENTS, 'Parents'),
        
    )
    Family_status = models.CharField(
        max_length= 20,
        choices= family_stat,
        default= PARENTS,
    )

    class_attend= models.IntegerField(null=True,blank=True)
    school= models.CharField(max_length=200, null=True,blank=True)
    father= models.CharField(max_length=200, null=True, blank=True)
    mother= models.CharField(max_length=200, null=True,blank=True)
    family_history= models.TextField(blank=False, default='none')
    # Proimage= models.ImageField(upload_to='media/', blank=True, null='True',default='default.png')
    


    def __str__(self):
        return self.name

    # def clean_name(self):
    #     return self.cleaned_data["name"].upper()
class image_students(models.Model):
    image = models.FileField(upload_to='media/', default='default.png')



    

records/forms.py
from django import forms
from .models import list_students,image_students


class listForm(forms.ModelForm):
   

    
    class Meta:
        model= list_students
        fields= '__all__'
        widgets={
            'name':forms.TextInput(attrs={'class': 'form-control'}),
            'birthdate':forms.DateInput(attrs={'class': 'form-control'}),
            
            'placeofbirth':forms.TextInput(attrs={'class': 'form-control'}),
            'class_attend':forms.TextInput(attrs={'class': 'form-control'}),
            'school':forms.TextInput(attrs={'class': 'form-control'}),
            'father':forms.TextInput(attrs={'class': 'form-control'}),
            'mother':forms.TextInput(attrs={'class': 'form-control'}),
            
        }

class ImageForm(forms.ModelForm):
    class Meta:
        model= image_students
        fields= '__all__'
    
        

records/views.py
from django.shortcuts import render
from records.models import list_students,image_students
from .forms import listForm,ImageForm
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth import  login, logout
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required





def students_list(request):
    list= list_students.objects.all()
    images = image_students.objects.all()
    
    return render(request, 'records/sasslist.html', {'list': list,'images':images})

def login(request):
    if request.method == 'POST':
        form= AuthenticationForm(data=request.POST)
        if form.is_valid():
            # if 'next' in request.POST:
            #     return redirect(request.POST.get('next'))
            # else:
             return redirect('/editmode1/')
    else:
         form= AuthenticationForm()
    return render(request, 'records/login.html',{'form':form})  
    

def register(request):
    if request.method== "POST":
        form= listForm(request.POST)
        if form.is_valid():
             
            list_students= form.save(commit=True)
            list_students.save()
            return redirect('/list/',)
            
    else:
        form= listForm()
        return render(request, 'records/register.html', {'form': form},)


@login_required(login_url='records:login')
def editmode(request):
    list= list_students.objects.all()
    images = image_students.objects.all()
    return render(request, 'records/editmode.html', {'list': list,'images':images})


def editmode1(request):
    list= list_students.objects.all()
    images = image_students.objects.all()
    return render(request, 'records/editmode.html', {'list': list,'images':images})
      

def upload(request):
     if request.method == 'POST':
        imgform = ImageForm(request.POST, request.FILES)
        if imgform.is_valid():
           
            imgform.save()
            
            return redirect('/list/',)
     else:
        imgform = ImageForm() # A empty, unbound form
        return render(request, 'records/upload.html',{'imgform':imgform})



    
  


def delete(request, pk):
   
    object = get_object_or_404(list_students, pk=pk)
    if request.method== "POST":
        object.delete()
        
        messages.success(request, 'messages successfully deleted')
        return redirect('/list/')
        
    else:
        
        return render(request, 'records/delete.html')



def edit(request, pk):
   
    list = get_object_or_404(list_students, pk=pk)
    if request.method == "POST":
        form = listForm(request.POST, instance=list)
        if form.is_valid():
            list = form.save(commit=True)
            list.name= str(request.user)
            
            return redirect('/list/')        
            
    else:
        form = listForm(instance=list)
    return render(request, 'records/register.html', {'form': form})

def search(request):
    if request.method=='POST':
        value= request.POST['name']
        if value:
            match= list_students.objects.filter(Q(name__icontains=value)  | Q(family_history__icontains=value))
            if match:
                return render(request,'records/search.html',{'srch':match})
            else:
                messages.error(request, "no match results")
        else:
            return redirect('/search/')    
    else:
        return render(request, 'records/sasslist.html')










    

records/templates/records/delete.html
{% extends 'records/sasslist.html' %}
{% block content %}
 <script>
     alert("are you sure you want to delete");
     

 </script>
 <form method="POST">
        {% csrf_token %}
<a href="{% url 'records:NameOfStudents' %}"><button type="submit">delete</button></a>
<a href="{% url 'records:NameOfStudents' %}"><button type="button">Cancel</button></a>
</form>
{% endblock %}

records/templates/records/editmode.html
{% extends 'records/sasslist.html' %}

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
      
                  <div class="col-md-12">
                      {% block content %}
                      <form id="searchform" action="{% url 'records:search' %}" method="get" accept-charset="utf-8">
                          <button class="searchbutton" type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                          <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
                        </form>
                    
                      <table class='table table-responsive-sm'>
                              <caption class="text-center"  style="color: rgb(20, 20, 43)">
                                  <H1>SAGARMATHA ASHAYA SEWA SANGH</H1>
                                  <h2>Gokarnashwor,Kathmandu, Nepal</h2>
                              </caption>
                              
                              <thead style="width: 110%!important;background: rgb(20, 20, 43);position: relative;">
                                  <tr style="color:white">
                                          <th>S.N.</th>
                                      <th>Name of Students</th>
                                      <th>Date Of Birth</th>
                                      <th>Place Of Birth</th>
                                      <th>Family Status</th>
                                      <th>Class Attended</th>
                                      <th>School Name</th>
                                      <th>Father Name</th>
                                      <th>Mother Name</th>
                                      <th>Family History</th>
                                      
                                      
  
                                  </tr>
                              </thead>
                              
                                  <tbody>
                             
                                  {% for lists in list %}<a href="#" data-toggle="modal" data-target="#popupModal">
  
                                              <tr class="th_style">
                                                  <td width='20px'>{{ forloop.counter }}</td>
                                                  <td>
                                             {{ lists.name }}
                                              </td>
                                              <td> {{ lists.birthdate }}</td>
                                              <td> {{ lists.placeofbirth }}</td>
                                              <td>{{ lists.Family_status }}</td>
                                              <td> {{ lists.class_attend }}</td>
                                              <td> {{ lists.school }}</td>
                                              <td> {{ lists.father }}</td>
                                              <td> {{ lists.mother }}</td>
                                              <td> {{ lists.family_history }}</td>
                                              <!-- <td><img src="{{ lists.Proimage.url }}" width="50px" height="50px"></td> -->
                                              <td>  
                                                {% for images in image %}
                                                {% if images.image %}
                                                    <img src="{{ images.image.url }}" height="50px" width="50px">
                                                {% endif %}
                                                {% endfor %}
                                            </td>
                                        </a>       
                                                    
  
  
                                                  <!-- for modals -->
                                                 
                                                        
                                            
  
  
                                                  <!-- end of modals -->
                                               
                                               <td><a href="{% url 'records:delete' pk=lists.pk %}">delete</a></td>
                                              
  
                                              <td><a href="{% url 'records:edit' pk=lists.pk %}">edit</a></td>
                                              
                                              </tr>
                           
                                   {% endfor %}
                                   </tbody>
                                   <tr>
                                       <td><a href="{% url 'records:registerstudents' %}">add new students</a></td>
                                   </tr>
                      </table>
                      
                      {% endblock %}
                  </div>
                  
    

records/templates/records/login.html
 {% extends 'records/sasslist.html' %}
 {% load crispy_forms_tags%}
 {% block content %} 
        <p>ehllo</p>
        {% if form.errors %}
             <p>your username or password is wrong</p>
        {% endif %}
        {% if next %}
          {% if user.is_authenticated %}
          <p>your account doesnot have access to it</p>
          {% else %}
          <p>please login to see</p>
          {% endif %}
          {% endif %}
        
           <div class="image" style="margin:9%"> 
               
              
                <!-- <img class="content-image" src="C:\Users\anil karki\dynamic\home\static\images" height="200px" width="200px"> -->
                
                                                        
            <form method="POST" action="{% url 'records:login' %}">
                <fieldset class="text-center"><H1>WELCOME TO LOGIN PAGE</H1>
                    
                    
                   
                    {{ form|crispy}}
                    {% csrf_token %}
                    <br>
                <!-- <p>{{form.password.label_tag }}</p><br>
                <p>{{ form.password }}</p> -->
                <!-- {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %} -->
               <button type="submit">login</button>
               
            
                
                </fieldset>
                
         
           
                    
                
                
            </form>
        </div>
        {% endblock %}
  
    


   

records/templates/records/logout.html
{% extends 'records/sasslilst.html' %}

{% block content %}
  <p>Logged out!</p>  
  <a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

records/templates/records/register.html
<style>
        .myfieldclass{
            background-color: green;
        }
    </style>
{% extends 'records/sasslist.html' %}
{% load crispy_forms_tags%}

{% block content %}
<h1>register the students</h1>
<div class="container-fluid">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  
   {% for field in form %}<br><br>
   <div class="col-sm-2"><label>{{field.label_tag}}</label></div>
   <div class="col-sm-9">
    {{field}}
    </div>
    
    {% endfor %}
<div class="col-sm-12">
    <a href="{% url 'records:NameOfStudents' %}"><button type="submit">register</button></a>
    <a href="{% url 'records:NameOfStudents' %}"><button type="button">Cancel</button></a>
    
</div>


   
</form>
<div class="col-sm-12">
    <br><br>
    
</div>


{% endblock %}

records/templates/records/sasslist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sagarmatha Ashaya Sewa Sangh</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'STYLE/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	
<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
<style>
  .searchfield{
    height: 40px;
    width: 250px;
    
    margin: 20px 0px 10px 10px;
  }
</style>



  
  <!-- <link rel="stylesheet" href="{% static 'records/css/bootstrap.min.css' %}" type="style/css"> -->

</head>
<body>
    <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <!-- {% for images in images %} -->
     {% if images.image %}
         <img src="{{ images.image.url }}" height="50px" width="50px">
     {% endif %}
     
     <!-- {% endfor %} -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{% url 'records:uploads' %}"><button type="button" class="btn btn-primary">Upload</button></a>
      </div>
    </div>
  </div>
</div>
    
                <div class="col-md-12">
                    {% block content %}
                    <form id="searchform" action="{% url 'records:search' %}" method="post" accept-charset="utf-8">
                        
                       <span style="float:right"> <input class="searchfield" id="searchbox" name="name" type="text" placeholder="Search" >
                        <button class="searchbutton" type="submit">
                            <i class="fas fa-search" style="height:14px;margin:10px;"></i>
                          </button>
                          <a href="{% url 'records:editmode' %}"><button type="button" class="btn btn-primary">
                              LOGIN
                            </button>
                          </a></span>
                        {% csrf_token %}
                      </form>
                  
                    <table class='table table-responsive-sm'>
                            <caption class="text-center"  style="color: rgb(20, 20, 43)">
                                <H1>SAGARMATHA ASHAYA SEWA SANGH</H1>
                                <h2>Gokarnashwor,Kathmandu, Nepal</h2>
                            </caption>
                            
                            <thead style="width: 110%!important;background: rgb(20, 20, 43);position: relative;">
                                <tr style="color:white">
                                        <th>S.N.</th>
                                    <th>Name of Students</th>
                                    <th>Date Of Birth</th>
                                    <th>Place Of Birth</th>
                                    <th>Family Status</th>
                                    <th>Class Attended</th>
                                    <th>School Name</th>
                                    <th>Father Name</th>
                                    <th>Mother Name</th>
                                    <th>Family History</th>
                                    <th>photo</th>
                                    

                                </tr>
                            </thead>
                            
                                <tbody>
                           
                                {% for lists in list %}

                                            <tr class="th_style">
                                                <td width='20px'>{{ forloop.counter }}</td>
                                                <td>
                                           {{ lists.name }}
                                            </td>
                                            <td> {{ lists.birthdate }}</td>
                                            <td> {{ lists.placeofbirth }}</td>
                                            <td>{{ lists.Family_status }}</td>
                                            <td> {{ lists.class_attend }}</td>
                                            <td> {{ lists.school }}</td>
                                            <td> {{ lists.father }}</td>
                                            <td> {{ lists.mother }}</td>
                                            <td> {{ lists.family_history }}</td>
                                            <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                                              Profile
                                            </button></td>
                                            
                                             <!-- <td><img src="{{ lists.Proimage.url }}" width="50px" height="50px"></td> -->
                                      </a>       

                                           <!-- for modals -->
                                               
                                                      
                                          


                                                <!-- end of modals -->
                                              
                                               
                                                
                                            
                                             <!-- <td><a href="{% url 'records:delete' pk=lists.pk %}">delete</a></td>
                                            

                                            <td><a href="{% url 'records:edit' pk=lists.pk %}">edit</a></td>
                                             -->
                                            </tr>
                         
                                 {% endfor %}
                                 
                                 </tbody>
                                
                    </table>
                    
                    {% endblock %}
                </div>
                
    </body>
</html>

records/templates/records/search.html
{% extends 'records/sasslist.html' %}
<div class="col-md-12">
    {% block content %}
    <form id="searchform" action="{% url 'records:search' %}" method="post" accept-charset="utf-8">
        <button class="searchbutton" type="submit">
          <i class="fa fa-search"></i>
        </button>
        <input class="searchfield" id="searchbox" name="name" type="text" placeholder="Search">
        {% csrf_token %}
      </form>
      
  
    <table class='table table-responsive-sm'>
            <caption class="text-center"  style="color: rgb(20, 20, 43)">
                <H1>SAGARMATHA ASHAYA SEWA SANGH</H1>
                <h2>Gokarnashwor,Kathmandu, Nepal</h2>
            </caption>
            
            <thead style="width: 110%!important;background: rgb(20, 20, 43);position: relative;">
                <tr style="color:white">
                        <th>S.N.</th>
                    <th>Name of Students</th>
                    <th>Date Of Birth</th>
                    <th>Place Of Birth</th>
                    <th>Family Status</th>
                    <th>Class Attended</th>
                    <th>School Name</th>
                    <th>Father Name</th>
                    <th>Mother Name</th>
                    <th>Family History</th>
                    <td>photo</td>
                    

                </tr>
            </thead>
            
                <tbody>
                   
                {% if srch %} 
                    {% for lists in srch %}
                        <a href="#" data-toggle="modal" data-target="#popupModal">

                            <tr class="th_style">
                                <td width='20px'>{{ forloop.counter }}</td>
                                <td>
                           {{ lists.name }}
                            </td>
                            <td> {{ lists.birthdate }}</td>
                            <td> {{ lists.placeofbirth }}</td>
                            <td>{{ lists.Family_status }}</td>
                            <td> {{ lists.class_attend }}</td>
                            <td> {{ lists.school }}</td>
                            <td> {{ lists.father }}</td>
                            <td> {{ lists.mother }}</td>
                            <td> {{ lists.family_history }}</td>
                            
                            <!-- <td><img src="{{ lists.Proimage.url }}" width="50px" height="50px"></td> -->
                      </a>       
                                  


                                <!-- for modals -->
                               
                                      
                          


                                <!-- end of modals -->
                              
                                <!-- {% for images in image %}
                                {% if images.image %} -->
                                    
                                <!-- {% endif %}
                                {% endfor %} 
                            
                             <!-- <td><a href="{% url 'records:delete' pk=lists.pk %}">delete</a></td>
                            

                            <td><a href="{% url 'records:edit' pk=lists.pk %}">edit</a></td>
                             -->
                            </tr>
         
                 {% endfor %}
                 <img src="{{ image_students.image.url }}" height="50px" width="50px">
                 </tbody>
                 <tr>
                     <td><a href="{% url 'records:editmode' %}">Login</a></td>
                 </tr>
                 
                {% endif %}
    </table>
    
    {% endblock %}
</div>

records/templates/records/upload.html
{% extends 'records/sasslist.html' %}

    {% block content %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <p>
            <input id="id_image" type="file" class="" name="image">
        </p>
       <a href="{% url 'records:uploads'  %}"> <input type="submit" value="Submit" /></a>
    </form> 



    {% endblock %}